---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cert-manager-volume
  namespace: kube-system
  labels:
    app: kube-cert-manager
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
