sudo: true
services:
- docker
language: go
env:
  global:
  - DOCKER_ORG=$(dirname ${TRAVIS_REPO_SLUG})
  - DOCKER_USERNAME=ctriv
  - secure: RjJy+MGaFHOfxEc5pKryfzrVE+sCME8q5iaULub2RaLuzSmpDjgJG1ArUTJBxkguHIRCIotd6zNsrrjXirVv9kZe3jvevOUJ8QJef59wP1YVpxkUPoM0yzdpdrIxOVrUzNFv/Hs2ydNp0PrWxJ+AcIpgOqqU4bktBaL50nwkv6+c/dv8f08KELrrNeMal8QJJzeDxQ//n0satx5/WMS4fnSZz5nveLiuIkvG4aHNWvgeinj3acgZZalbBtEZft1rhj3ok3SqT1pgXcUOhhbsaMMr8zcnKToJnWDFJ1GGoBDA81x3Tis4fLXbbhWidCyPAgOdFgd0IBeIMneZsfOE9F79teIFPaQATUotXkrNy8ULthCRDpLQx3DreyJh0ISIgb8Em8+GIneDY9dWypFQp8AfppSRAWhfMN7pThPfDaJJHJDQgmfoZHsnwE4w6Xk3PGScz23Ugl/HD3AYOGr0idHhly3y/1qEO5t8woRuoRuD3O6bUJMq4f65BevKpKCB7ILgS8FaAnkNHpr9NqXHFJXUlNIQ8rGPOQgnS0k8nh9K4sLdk2UKsEP+/UClucUC5ZEYGQ/D/8m5Gd4G+gJ8AzqwFxMJbFhQfmHnVZn6AUp0c47SsGkbw3RmXmJETyTrLHEDUd/iRH9H3rkEP1BKJ0ZYHeNVSCpVsliziwDMFhI=
go:
- 1.8.x
install:
- go get github.com/Masterminds/glide
- glide install
script:
- "./build.sh"
before_deploy:
- docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
deploy:
- provider: script
  script: docker build . -t ${DOCKER_ORG}/kube-cert-manager:master &&  docker push
    ${DOCKER_ORG}/kube-cert-manager:master
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: docker build . -t ${DOCKER_ORG}/kube-cert-manager:${TRAVIS_TAG} -t ${DOCKER_ORG}/kube-cert-manager:latest
    && docker push ${DOCKER_ORG}/kube-cert-manager:${TRAVIS_TAG} && docker push ${DOCKER_ORG}/kube-cert-manager:latest
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
