apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificates.stable.liquidweb.com
spec:
  scope: Namespaced
  group: stable.liquidweb.com
  version: v1
  names:
    kind: Certificate
    plural: certificates
    singular: certificate
    shortNames:
    - cert
    - certs
