kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-dir-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/cert-manager"