apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-cert-manager
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: kube-cert-manager
rules:
  - apiGroups: ["*"]
    resources: ["certificates", "ingresses", "certificate"]
    verbs: ["get", "list", "watch", "patch", "delete"]
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["*"]
    resources: ["events"]
    verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-cert-manager-service-account
subjects:
  - kind: ServiceAccount
    name: kube-cert-manager
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-cert-manager
  apiGroup: rbac.authorization.k8s.io